### PR TITLE
nowplaying/queue Command Fixes

### LINKED ISSUE #4: queue command hits character limit on long playlists
If a playlist is sufficiently long, the resulting message that it attempts to send exceeds the 2000 character limit on sendMessage().

### LINKED ISSUE #10: nowplaying and queue behave unexpectedly when player is inactive
Both the nowplaying and queue commands do not work correctly when the player has nothing in the queue. Queue simply outputs "Current Queue:", while the nowplaying command attempts to print the title of a null AudioTrack and throws an exception internally. Both should only need to check if the player is playing anything first, and act accordingly.

### PR DESCRIPTION
**Pull request by sasquench**
queue:

- prevent message character count from overflowing by only printing the first ten tracks in the queue (Closes #4)
- if the queue is empty, output a message stating such rather than just "Current Queue:" followed by no track names (Closes #10)

nowplaying:

- avoid trying to print out the name of the currently playing track when the player is inactive (Closes #10)

### CODE REVIEW

File: src/main/java/com/robothand/highqualitybot/command/NowPlayingCommand.java [hunk 1]
```diff
@@ -29,12 +30,19 @@ public String getShortDesc() {
     @Override
     public void onCommand(MessageReceivedEvent event, String[] args) {
         GuildMusicPlayer musicPlayer;
+        AudioTrack track;
         Guild guild = event.getGuild();
         MessageChannel channel = event.getChannel();
+        StringBuilder message = new StringBuilder();
```
Comment (pg8wood) [inline src/main/java/com/robothand/highqualitybot/command/NowPlayingCommand.java]: Might be good to call this messageBuilder or something just for good self-documenting codr
